### PR TITLE
Bump Ruby and Rails versions

### PR DESCRIPTION
**Pull request by cguess**
This bumps point releases of Ruby and Rails.

Run `rails t` to confirm it's all good.

### CODE REVIEW

**Review by reefdog — COMMENTED** [review]
When I `bundle install`, it generates the following change in the `Gemfile.lock`:

```diff
+ GIT
+   remote: https://github.com/TechAndCheck/YoutubeArchiver
+   revision: e1a594e9a6dcc7cfed3acdaabf55c92e9c3a6ab2
+   specs:
+     youtubearchiver (0.1.0)
+ 
- PATH
-   remote: /Users/christopher/Repositories/Reporters_Lab/YoutubeArchiver
-   specs:
-     youtubearchiver (0.1.0)
- 
```

Want me to commit that?

Also, I'm getting four errors when I run tests. But weirdly, I'm also getting four errors when running tests on `master`, but they're _different_ errors. 😵 Let's look at this together tomorrow!

**Comment by cguess** [comment]
Can you say which errors?

**Comment by reefdog** [comment]
Sure. `master`:

```
➜  hypatia git:(master) rails t
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Run options: --seed 10515

# Running:

.DEBUGGER: Attaching after process 79304 fork to child process 79329
{"error":"Error scraping spans","url":"https://www.facebook.com/AlanSChin","count":0}..unexpected character (after ) at line 1, column 2 [parse.c:769] for url https://www.instagram.com/p/CS17kK3n5-J
..E

Error:
ScraperControllerTest#test_forcing_a_scrape_works_and_renders_a_result:
Oj::ParseError: unexpected character (after ) at line 1, column 2 [parse.c:769]
    app/media_sources/instagram_media_source.rb:54:in `retrieve_instagram_post'
    app/media_sources/instagram_media_source.rb:27:in `extract'
    app/media_sources/media_source.rb:34:in `scrape!'
    app/media_sources/media_source.rb:15:in `scrape'
    app/controllers/scraper_controller.rb:20:in `scrape'
    test/controllers/scraper_controller_test.rb:158:in `block (2 levels) in <class:ScraperControllerTest>'
    test/controllers/scraper_controller_test.rb:157:in `block in <class:ScraperControllerTest>'


rails test test/controllers/scraper_controller_test.rb:156

..{"error":"Error scraping spans","url":"https://www.facebook.com/AlanSChin","count":0}..Downloading video MUaNz9M8fs8 @ 2022-05-19 22:04:47 -0500
Finished downloading video MUaNz9M8fs8 @ 2022-05-19 22:04:53 -0500
.E

Error:
ScraperControllerTest#test_scraping_an_instagram_image_with_force_works:
JSON::ParserError: unexpected character (after ) at line 1, column 2 [parse.c:769] in '{SNIPPED}'
    app/media_sources/instagram_media_source.rb:54:in `retrieve_instagram_post'
    app/media_sources/instagram_media_source.rb:27:in `extract'
    app/media_sources/media_source.rb:34:in `scrape!'
    app/media_sources/media_source.rb:15:in `scrape'
    app/controllers/scraper_controller.rb:20:in `scrape'
    test/controllers/scraper_controller_test.rb:104:in `block in <class:ScraperControllerTest>'


rails test test/controllers/scraper_controller_test.rb:103

E

Error:
ScraperControllerTest#test_scraping_an_instagram_video_with_force_works:
JSON::ParserError: unexpected character (after ) at line 1, column 2 [parse.c:769] in '{SNIPPED}'
    app/media_sources/instagram_media_source.rb:54:in `retrieve_instagram_post'
    app/media_sources/instagram_media_source.rb:27:in `extract'
    app/media_sources/media_source.rb:34:in `scrape!'
    app/media_sources/media_source.rb:15:in `scrape'
    app/controllers/scraper_controller.rb:20:in `scrape'
    test/controllers/scraper_controller_test.rb:111:in `block (2 levels) in <class:ScraperControllerTest>'
    test/controllers/scraper_controller_test.rb:110:in `block in <class:ScraperControllerTest>'


rails test test/controllers/scraper_controller_test.rb:109

...........E

Error:
InstagramMediaSourceTest#test_can_extract_post_without_an_error_being_posted_to_Slack:
JSON::ParserError: unexpected character (after ) at line 1, column 2 [parse.c:769] in '{SNIPPED}'
    app/media_sources/instagram_media_source.rb:54:in `retrieve_instagram_post'
    app/media_sources/instagram_media_source.rb:27:in `extract'
    test/media_sources/instagram_media_source_test.rb:20:in `block (2 levels) in <class:InstagramMediaSourceTest>'
    test/media_sources/instagram_media_source_test.rb:19:in `block in <class:InstagramMediaSourceTest>'


rails test test/media_sources/instagram_media_source_test.rb:18

.Downloading video Df7UtQTFUMQ @ 2022-05-19 22:05:52 -0500
Finished downloading video Df7UtQTFUMQ @ 2022-05-19 22:05:54 -0500
...

Finished in 182.250552s, 0.1591 runs/s, 0.2085 assertions/s.
29 runs, 38 assertions, 0 failures, 4 errors, 0 skips
```

Errors on `bump-rails`:

```
➜  hypatia git:(bump-rails) ✗ rails t                                 
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Run options: --seed 60672

# Running:

DEBUGGER: Attaching after process 77337 fork to child process 77392
{"error":"Error scraping spans","url":"https://www.facebook.com/AlanSChin","count":0}...Zorki encountered an error scraping Instagram for url https://www.instagram.com/p/CS17kK3n5-J
.E

Error:
InstagramMediaSourceTest#test_can_extract_post_without_an_error_being_posted_to_Slack:
Zorki::Error: Zorki encountered an error scraping Instagram
    app/media_sources/instagram_media_source.rb:54:in `retrieve_instagram_post'
    app/media_sources/instagram_media_source.rb:27:in `extract'
    test/media_sources/instagram_media_source_test.rb:20:in `block (2 levels) in <class:InstagramMediaSourceTest>'
    test/media_sources/instagram_media_source_test.rb:19:in `block in <class:InstagramMediaSourceTest>'


rails test test/media_sources/instagram_media_source_test.rb:18

........E

Error:
ScraperControllerTest#test_scraping_an_instagram_video_with_force_works:
Zorki::Error: Zorki encountered an error scraping Instagram
    app/media_sources/instagram_media_source.rb:54:in `retrieve_instagram_post'
    app/media_sources/instagram_media_source.rb:27:in `extract'
    app/media_sources/media_source.rb:34:in `scrape!'
    app/media_sources/media_source.rb:15:in `scrape'
    app/controllers/scraper_controller.rb:20:in `scrape'
    test/controllers/scraper_controller_test.rb:111:in `block (2 levels) in <class:ScraperControllerTest>'
    test/controllers/scraper_controller_test.rb:110:in `block in <class:ScraperControllerTest>'


rails test test/controllers/scraper_controller_test.rb:109

..E

Error:
ScraperControllerTest#test_scraping_an_instagram_image_with_force_works:
Zorki::Error: Zorki encountered an error scraping Instagram
    app/media_sources/instagram_media_source.rb:54:in `retrieve_instagram_post'
    app/media_sources/instagram_media_source.rb:27:in `extract'
    app/media_sources/media_source.rb:34:in `scrape!'
    app/media_sources/media_source.rb:15:in `scrape'
    app/controllers/scraper_controller.rb:20:in `scrape'
    test/controllers/scraper_controller_test.rb:104:in `block in <class:ScraperControllerTest>'


rails test test/controllers/scraper_controller_test.rb:103

{"error":"Error scraping spans","url":"https://www.facebook.com/AlanSChin","count":0}....E

Error:
ScraperControllerTest#test_forcing_a_scrape_works_and_renders_a_result:
Zorki::Error: Zorki encountered an error scraping Instagram
    app/media_sources/instagram_media_source.rb:54:in `retrieve_instagram_post'
    app/media_sources/instagram_media_source.rb:27:in `extract'
    app/media_sources/media_source.rb:34:in `scrape!'
    app/media_sources/media_source.rb:15:in `scrape'
    app/controllers/scraper_controller.rb:20:in `scrape'
    test/controllers/scraper_controller_test.rb:158:in `block (2 levels) in <class:ScraperControllerTest>'
    test/controllers/scraper_controller_test.rb:157:in `block in <class:ScraperControllerTest>'


rails test test/controllers/scraper_controller_test.rb:156

..Downloading video MUaNz9M8fs8 @ 2022-05-19 21:59:45 -0500
Finished downloading video MUaNz9M8fs8 @ 2022-05-19 21:59:52 -0500
..Downloading video Df7UtQTFUMQ @ 2022-05-19 22:00:23 -0500
Finished downloading video Df7UtQTFUMQ @ 2022-05-19 22:00:27 -0500
...

Finished in 113.643949s, 0.2552 runs/s, 0.3344 assertions/s.
29 runs, 38 assertions, 0 failures, 4 errors, 0 skips
```

**Review by reefdog — APPROVED** [review]
Tests run clean! 🎉 🚀

**Pull request merged**
