### PR TITLE
Fix Screenshot Paramaters

### PR DESCRIPTION
**Pull request by cguess**
This moves screenshot parameter from named to locational

To test, run the tests. This doesn't change any functionality.

### CODE REVIEW

**Comment by oneroyalace** [comment]
Ah, this is based off #53. Will this be merged after it? Merged into it?

**Comment by cguess** [comment]
After

-Christopher Guess
***@***.***
US/WhatsApp/Signal: +1 262.893.1037
PGP: AAE7 5171 0D81 B45B – https://keybase.io/cguess

**Comment by cguess** [comment]
Test

**Comment by oneroyalace** [comment]
```
E                                                                                                                                                                                 
                                                                                         
Error:                                                                                                                                                                            
YoutubeMediaSourceTest#test_extracted_video_is_not_uploaded_to_S3_if_AWS_REGION_isn't_set_and_does_have_Base64_in_JSON_version:                                                   
Selenium::WebDriver::Error::UnknownError: [Exception... "Data conversion failed because significant data would be lost"  nsresult: "0x80460003 (NS_ERROR_LOSS_OF_SIGNIFICANT_DATA)"  location: "<unknown>"  data: no]                                                                                                                                               
    app/media_sources/media_source.rb:60:in `take_screenshot'                                                                                                                     
    app/media_sources/youtube_media_source.rb:79:in `block in retrieve_youtube_video'    
    app/media_sources/youtube_media_source.rb:78:in `each'                                                                                                                        
    app/media_sources/youtube_media_source.rb:78:in `retrieve_youtube_video'                                                                                                      
    app/media_sources/youtube_media_source.rb:33:in `extract'                                                                                                                     
    test/media_sources/youtube_media_source_test.rb:69:in `block (2 levels) in <class:YoutubeMediaSourceTest>'                                                                    
    test/test_helper.rb:23:in `modify_environment_variable'                                                                                                                       
    test/media_sources/youtube_media_source_test.rb:68:in `block in <class:YoutubeMediaSourceTest>'           
    ```

**Comment by cguess** [comment]
OK, this is weird, and actually a C level issue (NS_ERROR_LOSS_OF_SIGNIFICANT_DATA is a macOS OS-level bug).

Have you tried this since upgrading Chrome?

**Comment by oneroyalace** [comment]
I have not, but I'll do so now!

**Comment by oneroyalace** [comment]
Merged in #65

**Pull request closed without merging**
